### ISSUE TITLE
Tooltip missing

### ISSUE THREAD

**Issue by Kaimberex** [p3lim-wow/BonusRollPreview#36] opened 2019-03-22 01:53 UTC
when hoving over items in BRP frame its met with a blank box. You can tell something is supposed to be there but its just a blank box. No other addons are loaded.  
![InkedWoWScrnShot_032119_204934_LI](https://user-images.githubusercontent.com/37189369/54795663-23cd5d00-4c1b-11e9-81b2-eb093fd96ce4.jpg)

- What version are you using? 80100.47-Release
- Can the issue be reproduced, and if so, how? Yes, kill any boss that produces a bonus roll event 
- If there was an error message, please include it.
- If there is a graphical issue, please include a screenshot (you can drag-n-drop here).

Make sure you check back often until the issue is resolved for any follow-up questions.

**Comment by Ookami313** [comment] 2019-03-27 21:26
Unsure if it's related or not to this ticket (was going to open a new ticket but saw this one and thought I'd add my issue to it since it may be related), but this is what I'm getting now after killing a boss. I get the pull up listing the items dropped that are relevant to my character, but nothing shows in the tool tip and it looks like internal icons are all over the place in some instances. Thanks.

![WoWScrnShot_032719_005649-BRP glitch](https://user-images.githubusercontent.com/26803942/55113368-56f96b80-50b5-11e9-9869-8d70bfc5e542.jpg)

**Comment by Kaimberex** [comment] 2019-03-27 22:36
> 
> 
> Unsure if it's related or not to this ticket (was going to open a new ticket but saw this one and thought I'd add my issue to it since it may be related), but this is what I'm getting now after killing a boss. I get the pull up listing the items dropped that are relevant to my character, but nothing shows in the tool tip and it looks like internal icons are all over the place in some instances. Thanks.
> 
> ![WoWScrnShot_032719_005649-BRP glitch](https://user-images.githubusercontent.com/26803942/55113368-56f96b80-50b5-11e9-9869-8d70bfc5e542.jpg)

this was also my experience I even reset my complete interface and had only this addon loaded and no others and I was met with what you are seeing as well.

**Comment by Addonman** [comment] 2019-04-08 11:23
Same here

**Comment by Calesta** [comment] 2019-04-13 17:02
Any news on a fix for this issue?  I see some replies from p3lim in some of the open cases but none are recent.

**Comment by ztbsuper** [comment] 2019-05-04 09:58
hi there, i've tried to fix this issue , though I'm not good at WOWUI/lua, but I surppose that the Compare dialog is frozen so that it may cause by anchor or something else...

I fixed it in file BonusRollPreview.xml, at 222 line, before the GameTooltip:SetHyperlink(self.itemLink), add the code below:
```lua
GameTooltip_SetDefaultAnchor(GameTooltip, UIParent)
```
code piece:
```lua
if(self.itemLink) then
	GameTooltip:SetOwner(self, 'ANCHOR_NONE')
	GameTooltip:ClearAllPoints()
	GameTooltip:SetPoint('TOPRIGHT', self, 'TOPLEFT')
	GameTooltip_SetDefaultAnchor(GameTooltip, UIParent)
	GameTooltip:SetHyperlink(self.itemLink)
	self:RegisterEvent('MODIFIER_STATE_CHANGED')
end
```

if it works, please comment

**Comment by Addonman** [comment] 2019-05-04 11:39
I seems to work.I did world boss and i could see items normaly now.Since it seems you know what problem was can you take a quikl look at this other addon that has same issue?
https://github.com/anhility/BestInSlotRedux/issues/55
Basicly when you check addon and try to look at items it shows same black square.I tried to input line when i thought it would be similary looking code but i didnt work .

**Comment by p3lim** [comment] 2019-05-04 12:23
Sorry for being unresponsive, a lot going on these days.
I've taken a look at the issue, but I'm unable to reproduce it myself.
The "fix" by @ztbsuper will reset the position of the tooltip entirely, appearing in the bottom-right position on the screen, which is not something we want.

What resolutions are you all using?

**Comment by ztbsuper** [comment] 2019-05-04 12:26
> Sorry for being unresponsive, a lot going on these days.
> I've taken a look at the issue, but I'm unable to reproduce it myself.
> The "fix" by @ztbsuper will reset the position of the tooltip entirely, appearing in the bottom-right position on the screen, which is not something we want.
> 
> What screen resolutions are you all using?

1920*1080
Full screen(window model)

**Comment by Humwq** [comment] 2019-05-04 12:59
> 
> 
> hi there, i've tried to fix this issue , though I'm not good at WOWUI/lua, but I surppose that the Compare dialog is frozen so that it may cause by anchor or something else...
> 
> I fixed it in file BonusRollPreview.xml, at 222 line, before the GameTooltip:SetHyperlink(self.itemLink), add the code below:
> 
> ```lua
> GameTooltip_SetDefaultAnchor(GameTooltip, UIParent)
> ```
> 
> code piece:
> 
> ```lua
> if(self.itemLink) then
> 	GameTooltip:SetOwner(self, 'ANCHOR_NONE')
> 	GameTooltip:ClearAllPoints()
> 	GameTooltip:SetPoint('TOPRIGHT', self, 'TOPLEFT')
> 	GameTooltip_SetDefaultAnchor(GameTooltip, UIParent)
> 	GameTooltip:SetHyperlink(self.itemLink)
> 	self:RegisterEvent('MODIFIER_STATE_CHANGED')
> end
> ```
> 
> if it not work, please comment

The problem has not been resolved.

**Comment by p3lim** [comment] 2019-05-04 13:14
I've found the issue, it's something with the compare tooltips, I'll wager some, if not all of you have "always compare" turned on. You can check with this:
```
/dump GetCVarBool('alwaysCompareItems')
```

Now I know what the issue is, should be easy to fix.

**Comment by ztbsuper** [comment] 2019-05-04 13:17
![image](https://user-images.githubusercontent.com/2212606/57179582-f4646e00-6eb1-11e9-8408-10bd75667418.png)

**Comment by p3lim** [comment] 2019-05-04 13:47
Please test if that solved it and I'll release a new version.

**Closed** 2019-05-04 13:47 UTC

**Comment by Humwq** [comment] 2019-05-05 13:03
https://i.imgur.com/G9FZae8.png
